package main

import (
	"context"
	"fmt"
	"net/http"
	"time"

	cowclickerv1 "cowclicker-grpc-api/gen/go/cowclicker/v1"                  // generated by protoc-gen-go
	cowclickerv1connect "cowclicker-grpc-api/gen/go/cowclicker/v1/v1connect" // generated by protoc-gen-connect-go
)

type CowclickerServer struct{}

func (s *CowclickerServer) Click(
	ctx context.Context,
	req *cowclickerv1.ClickRequest,
) (*cowclickerv1.ClickResponse, error) {
	res := &cowclickerv1.ClickResponse{
		ServerReceivedEpochMs: time.Now().UnixMilli(),
		ServerSentEpochMs:     time.Now().UnixMilli(),
		ClickCount:            1,
	}
	return res, nil
}

func main() {
	server := &CowclickerServer{}
	mux := http.NewServeMux()
	path, handler := cowclickerv1connect.NewClickServiceHandler(server)
	mux.Handle(path, handler)
	p := new(http.Protocols)
	p.SetHTTP1(true)
	// Use h2c so we can serve HTTP/2 without TLS.
	p.SetUnencryptedHTTP2(true)
	addr := "localhost:8080"
	s := http.Server{
		Addr:      addr,
		Handler:   mux,
		Protocols: p,
	}
	fmt.Println("Server is running on", addr)
	s.ListenAndServe()
}
